### ISSUE TITLE
NameError: name 'R' is not defined

### ISSUE THREAD

**Issue by firmianay** [SPRITZ-Research-Group/SPECK#2]
```
$ python3 Scan.py -s ~/app/BluetoothMusic.apk -f -p ~/Android/Sdk/platforms/
[!] Analysing BluetoothMusic

[#] RULE 1
[=>] Show an App Chooser
[=>] 62/62 file(s) analysed

[?] FlowDroid option detected
[?] FlowDroid is running...
[?] FlowDroid has finished

Traceback (most recent call last):
  File "Scan.py", line 130, in <module>
    scan.run()
  File "Scan.py", line 110, in run
    self.analyse()
  File "Scan.py", line 101, in analyse
    rulefct.run()
  File "/home/firmy/SPECK/server/codeAnalysis/Rules/Rule1.py", line 121, in run
    self.store(1, self.AndroidOkMsg, self.AndroidErrMsg, self.AndroidText, self.category, False, [self.errMsg])
  File "/home/firmy/SPECK/server/codeAnalysis/Rules/Rules.py", line 138, in store
    self.results, self.statFiles = fdroid.run(self.results, self.statFiles)
  File "/home/firmy/SPECK/server/codeAnalysis/FlowDroid.py", line 177, in run
    return f.start(results, statFiles)
  File "/home/firmy/SPECK/server/codeAnalysis/flowdroid/FlowDroidRule1.py", line 16, in start
    results, statFiles = self.GoodButBad(results, statFiles)
  File "/home/firmy/SPECK/server/codeAnalysis/flowdroid/FlowDroidRule1.py", line 34, in GoodButBad
    bad_location = err[R.PATH]
NameError: name 'R' is not defined
```

**Comment by mollysec** [comment]
Hi, thank you for reporting the issue. It should be fixed now (<https://github.com/SPRITZ-Research-Group/SPECK/commit/72ab33dc687e10fb7cd3448ea2a7523f7471a5f9>). 
The problem was that some FlowDroidRules files didn't import the R and Parser classes.
For the moment, I am going to close the issue. Feel free to reopen it if the issue persists.
